const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const SOURCE_CARDS'));
new vm.Script(script);
const storage=new Map();
const context=vm.createContext({window:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console});
vm.runInContext(script.slice(0,script.indexOf('function safeLocalSave')),context);
const run=s=>vm.runInContext(s,context);
assert(run('state.cards.length')>0);
assert.equal(run('semesters["5"].cards.length'),100);
assert.equal(run('semesters["5"].cards.filter(c=>c.subject==="Datenbanken").length'),33);
assert.equal(run('semesters["5"].cards.filter(c=>c.subject==="Theoretische Informatik").length'),67);
assert(run('semesters["5"].cards.every(c=>c.topic && c.definition && c.question && c.note)'));
assert.equal(run('new Set(defaults.map(c=>c.id)).size'),run('defaults.length'));
assert.equal(run('new Set(TI_REVIEW_CARDS.map(c=>c.topic)).size'),3);
assert(run('semesters["4"].cards.every(c=>!["Datenbanken","Theoretische Informatik"].includes(c.subject))'));
assert.equal(run('normalizeState({cards:[]},"5").cards.length'),100);
assert.equal(run('normalizeState({cards:[],deletedIds:["doc_db_intro_001"]},"5").cards.length'),99);
assert.equal(run('normalizeState({cards:semesters["5"].cards.filter(c=>c.subject==="Datenbanken")},"5").cards.length'),100);
assert.equal(run('normalizeState({cards:[],deletedIds:["doc_ti_intro_001"]},"5").cards.filter(c=>c.subject==="Theoretische Informatik").length'),66);
assert.equal(run('normalizeState({cards:[{...TI_REVIEW_CARDS[0],reviews:8,definition:"Edited TI answer"}]},"5").cards.find(c=>c.id==="doc_ti_intro_001").reviews'),8);
assert.equal(run('normalizeState({cards:[{...TI_REVIEW_CARDS[0],definition:"Edited TI answer"}]},"5").cards.find(c=>c.id==="doc_ti_intro_001").definition'),'Edited TI answer');
assert.equal(run('normalizeState({cards:[{...semesters["5"].cards[0],reviews:6,definition:"Edited answer"}]},"5").cards[0].reviews'),6);
assert.equal(run('normalizeState({cards:[{...semesters["5"].cards[0],definition:"Edited answer"}]},"5").cards[0].definition'),'Edited answer');
assert.equal(run('semesters["5"].subjects.length'),3);
run('state.cards[0].reviews=7;state.sessions.today={reviews:9};state.history.push({id:state.cards[0].id,subject:state.cards[0].subject});');
const legacy=run('JSON.stringify(state)');
context.legacy=JSON.parse(legacy);
run('state=restoreSemesters(legacy)');
assert.equal(run('state.cards[0].reviews'),7);
assert.equal(run('state.sessions.today.reviews'),9);
assert.equal(run('semesters["5"].history.length'),0);
run('activeSemester="5";state=semesters["5"];state.cards.push({id:"custom_test",custom:true,subject:"Datenbanken",reviews:2});state.sessions.today={reviews:2};state.subjects.push("Neues Fach")');
const rename=script.slice(script.indexOf('function renameSubject('),script.indexOf('function manageSubjects('));
vm.runInContext(rename,context);
run('renameSubject("Datenbanken","Datenbanken II");state=restoreSemesters(JSON.parse(JSON.stringify(snapshot())))');
assert.equal(run('state.cards.length'),101);
assert.equal(run('state.cards[0].subject'),'Datenbanken II');
assert.equal(run('state.subjects.includes("Datenbanken")'),false);
assert.equal(run('state.subjects.includes("Neues Fach")'),true);
assert.equal(run('semesters["4"].cards[0].reviews'),7);
assert.equal(run('semesters["4"].sessions.today.reviews'),9);
run('state.sessions={};state.history=[];state.cards=state.cards.map(c=>({...c,reviews:0}));snapshot()');
assert.equal(run('semesters["4"].cards[0].reviews'),7);
assert.equal(run('semesters["4"].history.length'),1);
run('activeSemester="4";state=semesters["4"];renameSubject(state.subjects[0],"Renamed");state=restoreSemesters(JSON.parse(JSON.stringify(snapshot())))');
assert.equal(run('state.cards[0].subject'),'Renamed');
assert.equal(run('state.subjects[0]'),'Renamed');
console.log('Passed: script syntax, legacy migration, semester isolation, persistence, subject rename, custom subjects and reset isolation.');
