const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const SOURCE_CARDS'));
new vm.Script(script);
const storage=new Map();
const context=vm.createContext({window:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console});
vm.runInContext(script.slice(0,script.indexOf('function safeLocalSave')),context);
const run=s=>vm.runInContext(s,context);
assert(run('state.cards.length')>0);
assert.equal(run('semesters["5"].cards.length'),0);
assert.equal(run('semesters["5"].subjects.length'),3);
run('state.cards[0].reviews=7;state.sessions.today={reviews:9};state.history.push({id:state.cards[0].id,subject:state.cards[0].subject});');
const legacy=run('JSON.stringify(state)');
context.legacy=JSON.parse(legacy);
run('state=restoreSemesters(legacy)');
assert.equal(run('state.cards[0].reviews'),7);
assert.equal(run('state.sessions.today.reviews'),9);
assert.equal(run('semesters["5"].history.length'),0);
run('activeSemester="5";state=semesters["5"];state.cards.push({id:"custom_test",custom:true,subject:"Datenbanken",reviews:2});state.sessions.today={reviews:2};state.subjects.push("Neues Fach")');
const rename=script.slice(script.indexOf('function renameSubject('),script.indexOf('function manageSubjects('));
vm.runInContext(rename,context);
run('renameSubject("Datenbanken","Datenbanken II");state=restoreSemesters(JSON.parse(JSON.stringify(snapshot())))');
assert.equal(run('state.cards.length'),1);
assert.equal(run('state.cards[0].subject'),'Datenbanken II');
assert.equal(run('state.subjects.includes("Datenbanken")'),false);
assert.equal(run('state.subjects.includes("Neues Fach")'),true);
assert.equal(run('semesters["4"].cards[0].reviews'),7);
assert.equal(run('semesters["4"].sessions.today.reviews'),9);
run('state.sessions={};state.history=[];state.cards=state.cards.map(c=>({...c,reviews:0}));snapshot()');
assert.equal(run('semesters["4"].cards[0].reviews'),7);
assert.equal(run('semesters["4"].history.length'),1);
run('activeSemester="4";state=semesters["4"];renameSubject(state.subjects[0],"Renamed");state=restoreSemesters(JSON.parse(JSON.stringify(snapshot())))');
assert.equal(run('state.cards[0].subject'),'Renamed');
assert.equal(run('state.subjects[0]'),'Renamed');
console.log('Passed: script syntax, legacy migration, semester isolation, persistence, subject rename, custom subjects and reset isolation.');
